package com.openlingo.app.grammar.drills

import com.openlingo.app.data.local.models.ChallengeType
import com.openlingo.app.data.repository.ChallengeWithOptions
import com.openlingo.app.grammar.AnswerGrader
import com.openlingo.app.grammar.BlankPlaceholder

/**
 * Turns the shipped curriculum into conjugation drills.
 *
 * Spanish and Japanese conjugation are systematic, so a drill does not need content
 * authored for it: it needs the content the curriculum already has, regrouped.
 *
 * ## Where the data ends and the code begins
 *
 * Read from the payloads, never computed here:
 * - **the grouping key** — `ChallengeEntity.grammaticalFocus`. Paradigms are literally
 *   `challenges.groupBy { it.grammaticalFocus }`; there is no list of paradigms in this
 *   file, no language switch, and no per-focus branch.
 * - **the inflected forms** — the `acceptedAnswers` of a `FILL_BLANK` row, else the text
 *   of its single `correct` option. A form is never generated by conjugating anything.
 * - **the near-misses** — the incorrect options' `text` and their `errorTag`, verbatim.
 * - `ruleText`, `romaji` and the answer option's `audioSrc`, verbatim.
 *
 * The only things this object decides, and which are therefore the whole authoring
 * contract a new paradigm has to meet:
 * 1. the two mechanics that produce one form ([FORM_MECHANICS]),
 * 2. the two prompt shapes that name a lemma and a slot ([LEMMA], [QUOTED_SLOT], [BARE_SLOT]),
 * 3. that a near-miss is of the same word when its tag names a form error and it shares
 *    a stem with the answer ([isSameLemma]),
 * 4. that a form taught twice is one row ([merge]).
 *
 * Those are the shapes the corpus already uses for every paradigm it drills, so a new
 * paradigm is authored the ordinary way. Add `CONJUGATE`/`FILL_BLANK` challenges under a
 * new slug and they appear in the drill: **no new drill code.**
 *
 * It is a pure function of the payloads: no database, no Android, no clock, so it is
 * unit-testable on the JVM and the screen stays a rendering concern. It also never
 * writes: a drill is a study surface, and nothing here touches `challenge_progress`,
 * `mistakes` or `exercise_type_stats`, so browsing one cannot change what the app
 * thinks the learner is weak at.
 */
object StructureDrill {

    /**
     * The two mechanics that ask the learner to produce exactly one conjugated form.
     *
     * `CONJUGATE` names the form in its prompt and offers one right answer among
     * near-misses; `FILL_BLANK` leaves a `___` in a sentence and accepts a typed form in
     * `acceptedAnswers`. The recognition mechanics (SELECT, LISTEN, ASSIST, STORY,
     * MATCH_PAIRS) and the assembly mechanic (WORD_BANK) do not: their answer is a
     * sentence or a phrase, and a sentence is not a row of a conjugation table. This
     * restriction also does the work a length or word-count heuristic would have to do
     * for Japanese, where a whole clause and a single verb form are both whitespace-free.
     */
    private val FORM_MECHANICS = setOf(ChallengeType.CONJUGATE, ChallengeType.FILL_BLANK)

    /**
     * One paradigm per focus that has extractable material, in first-seen order.
     *
     * Focuses with nothing extractable are absent rather than present-and-empty, so a
     * caller can drive a focus selector straight off this list. Use [paradigm] when a
     * specific focus is known and may legitimately be empty.
     */
    fun paradigms(challenges: List<ChallengeWithOptions>): List<Paradigm> {
        val byFocus = LinkedHashMap<String, MutableList<ParadigmEntry>>()
        for (challenge in challenges) {
            val entry = entryFor(challenge) ?: continue
            val entries = byFocus.getOrPut(entry.focus) { mutableListOf() }
            val existing = entries.indexOfFirst {
                AnswerGrader.normalize(it.form) == AnswerGrader.normalize(entry.form)
            }
            if (existing < 0) {
                entries.add(entry)
            } else {
                entries[existing] = merge(entries[existing], entry)
            }
        }
        return byFocus.map { (focus, entries) -> Paradigm(focus = focus, entries = entries.toList()) }
    }

    /**
     * The paradigm for [focus] within [challenges], empty rather than absent when the
     * corpus teaches nothing drillable under that slug.
     *
     * A focus with no paradigm is a normal state — a newly authored focus before its
     * first form-bearing challenge, or a focus whose material is all recognition — so
     * callers render an empty state rather than failing.
     */
    fun paradigm(challenges: List<ChallengeWithOptions>, focus: String): Paradigm =
        paradigms(challenges).firstOrNull { it.focus == focus }
            ?: Paradigm(focus = focus, entries = emptyList())

    /**
     * Folds two rows for the same form of the same paradigm into one.
     *
     * A form is usually taught more than once — `vivía` is both the answer to a blanked
     * sentence and the answer to "which imperfect form of *vivir* goes with 'yo'". A
     * table that listed it twice would read as two different conjugations, so the rows
     * merge and the learner gets one row carrying every accepted spelling and every
     * near-miss. The base row is the one that names a lemma or a slot, because that is
     * the one with a label worth showing.
     */
    private fun merge(a: ParadigmEntry, b: ParadigmEntry): ParadigmEntry {
        val base = when {
            a.lemma != null && b.lemma == null -> a
            b.lemma != null && a.lemma == null -> b
            a.slot != null && b.slot == null -> a
            b.slot != null && a.slot == null -> b
            else -> a
        }
        val other = if (base === a) b else a
        return base.copy(
            accepted = (base.accepted + other.accepted).distinct(),
            distractors = (base.distractors + other.distractors).distinctBy { it.form to it.errorTag },
            ruleText = base.ruleText ?: other.ruleText,
            romaji = base.romaji ?: other.romaji,
            audioSrc = base.audioSrc ?: other.audioSrc,
        )
    }

    /** The drillable row for one challenge, or null when it teaches no single form. */
    private fun entryFor(withOptions: ChallengeWithOptions): ParadigmEntry? {
        val challenge = withOptions.challenge
        val focus = challenge.grammaticalFocus?.trim().orEmpty()
        if (focus.isEmpty()) return null
        if (challenge.type !in FORM_MECHANICS) return null

        // Held-out rows are the checkpoint's half of the corpus: the learner is meant to
        // meet the structure for the first time under test. The lesson-path query
        // already excludes them, and this is the belt to that braces — a drill must
        // never be the thing that reveals one.
        if (challenge.heldOut) return null

        val correct = withOptions.options.filter { it.correct }
        // Anything other than exactly one correct option is not one conjugated form: none
        // at all is a row with no answer, and several is a sentence being assembled.
        if (correct.size != 1) return null

        val authored = AnswerGrader.acceptedVariants(challenge.acceptedAnswers)
        val answerOption = correct.single()
        val form = (authored.firstOrNull() ?: answerOption.text).trim()
        if (form.isEmpty()) return null

        val distractors = distractorsFor(withOptions, form)
        val lemma = lemmaOf(challenge.question)
        val hasFrame = lemma != null || BlankPlaceholder.parse(challenge.question) != null
        // Without a frame and without a same-lemma near-miss, this item is about a word,
        // not about a form, whatever its focus says.
        if (!hasFrame && distractors.none { isSameLemma(it, form) }) return null

        return ParadigmEntry(
            challengeId = challenge.id,
            lessonId = challenge.lessonId,
            focus = focus,
            form = form,
            accepted = (authored + answerOption.text)
                .map { it.trim() }
                .filter { it.isNotEmpty() }
                .distinct(),
            prompt = challenge.question,
            slot = slotOf(challenge.question),
            lemma = lemma,
            ruleText = challenge.ruleText,
            romaji = answerOption.romaji,
            // Only audio authored *for this form*. A challenge-level clip is the whole
            // sentence, and playing that when the learner asked to hear `vivía` teaches
            // the wrong thing; the screen speaks the form instead when this is null.
            audioSrc = answerOption.audioSrc,
            distractors = distractors,
        )
    }

    /**
     * Every incorrect option that carries a curriculum `errorTag`, minus the one that is
     * simply the answer written differently.
     *
     * Comparison goes through [AnswerGrader.normalize] so a distractor differing only by
     * an accent or by an IME's full-width forms is not offered as a mistake the learner
     * could not have made.
     */
    private fun distractorsFor(withOptions: ChallengeWithOptions, form: String): List<ParadigmDistractor> {
        val answer = AnswerGrader.normalize(form)
        return withOptions.options
            .filterNot { it.correct }
            .filter { AnswerGrader.normalize(it.text) != answer }
            .mapNotNull { option -> option.errorTag?.let { ParadigmDistractor(option.text, it) } }
    }

    /**
     * True when [distractor] is another form of the same word: the tag names a
     * morphological or register error rather than a different word, and the two strings
     * share a stem.
     *
     * The stem is what separates "the paradigm" from "the neighbourhood". In a ser/estar
     * challenge `están` is tagged `WRONG_PERSON`, but it shares nothing with the answer,
     * so it is not a conjugation of it.
     */
    private fun isSameLemma(distractor: ParadigmDistractor, form: String): Boolean =
        distractor.errorTag in ErrorTag.SAME_LEMMA && sharesStem(distractor.form, form)

    private fun sharesStem(a: String, b: String): Boolean {
        val left = AnswerGrader.normalize(a)
        val right = AnswerGrader.normalize(b)
        val limit = minOf(left.length, right.length)
        for (i in 0 until limit) {
            if (left[i] != right[i]) return i > 0
        }
        return limit > 0
    }

    /** `Which preterite form of hablar goes with 'nosotros'?` -> `hablar`. */
    private fun lemmaOf(question: String): String? = LEMMA.find(question)?.groupValues?.get(1)?.trim()

    /**
     * The person or frame the form fills: the quoted slot when the prompt quotes one
     * ("goes with 'nosotros'", "means 'I can speak'"), otherwise the bare Japanese slot
     * ("goes with ください"). Null when the prompt names neither, in which case the
     * blanked sentence is the label.
     */
    private fun slotOf(question: String): String? =
        QUOTED_SLOT.find(question)?.groupValues?.get(1)?.cleanSlot()
            ?: BARE_SLOT.find(question)?.groupValues?.get(1)?.cleanSlot()

    private fun String.cleanSlot(): String? = trim().trimEnd('?').trim().ifEmpty { null }

    private val LEMMA = Regex("""form of (?:the verb )?(\S+?)(?=\s+(?:goes|belongs|fits|means)\b)""")
    private val QUOTED_SLOT = Regex("""(?:goes|belongs|fits|means)\s+(?:with\s+)?['"]([^'"]+)['"]""")
    private val BARE_SLOT = Regex("""(?:goes|belongs|fits)\s+with\s+(\S+)""")
}
